# Generated by Django 2.2.9 on 2020-09-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ornament_mac_address',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
