# Generated by Django 2.2.9 on 2020-12-07 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ornaments', '0002_nickname'),
        ('logger', '0002_log_ornament_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='ornament_mac_address',
        ),
        migrations.AddField(
            model_name='log',
            name='ornament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ornaments.OrnamentDevice'),
            preserve_default=False,
        ),
    ]
