apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: northpole
  labels:
    app: northpole
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: northpole
    spec:
      containers:
      - name: northpole-app
        # Replace  with your project ID or use `make template`
        image: gcr.io/northpole/northpole
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        ports:
        - containerPort: 8080


      # [START volumes]
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
      # [END volumes]
# [END kubernetes_deployment]

---

# [START service]
# The northpole service provides a load-balancing proxy over the northpole app
# pods. By specifying the type as a 'LoadBalancer', Container Engine will
# create an external HTTP load balancer.
# For more information about Services see:
#   https://cloud.google.com/container-engine/docs/services/
# For more information about external HTTP load balancing see:
#   https://cloud.google.com/container-engine/docs/load-balancer
apiVersion: v1
kind: Service
metadata:
  name: northpole
  labels:
    app: northpole
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: northpole
# [END service]