# Generated by Django 3.0 on 2020-02-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ornaments', '0001_ornament_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ornamentdevice',
            name='nickname',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
